name: Create new branch
on:
  issues:
    types:
      - opened

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - run: |
          git config user.name
          git config user.email
        # env:
        #   GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   ISSUE: ${{ github.event.issue.html_url }}
