name: Create new branch
on:
  issues:
    types:
      - opened

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - run: |
          git checkout -b new-branch
          echo "hello" >> my-new-file.txt
          git add -A
          git commit -m "added new file"
          git push origin new-branch
        # env:
        #   GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   ISSUE: ${{ github.event.issue.html_url }}
