name: Update Submodule
on:
  repository_dispatch:
    types:
      - update-submodule
jobs:
  update-submodule:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive
      - name: Make changes (update submodule)
        run: |
          git submodule update --init --recursive --remote -f
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT }}
          commit_message: Update submodule
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: update-submodule
          delete-branch: true
          title: Update Submodule
          body: |
            Update Submodule
            - blah blah
            - yap yap
          assignees: peter-bread
          reviewers: peter-bread
          draft: false
        
